name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Tests
      id: tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Tests
        setup-command: ''
        command: "./test.sh"
        timeout: 10
        max-score: 20
    - name: Valgrind
      id: valgrind
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Valgrind
        setup-command: sudo apt-get install -y valgrind
        command: "./valgrind.sh"
        timeout: 10
        max-score: 15
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS_RESULTS: "${{steps.tests.outputs.result}}"
        VALGRIND_RESULTS: "${{steps.valgrind.outputs.result}}"
      with:
        runners: tests,valgrind
